export const actions = {
  TOAST_ADD: 'TOAST_ADD',
  TOAST_REMOVE_OLDEST: 'TOAST_REMOVE_OLDEST',
  TODOS_SET: 'TODOS_SET',
  TODOS_UPDATE_SELECTION: 'TODOS_UPDATE_SELECTION',
  TODOS_UPDATE_SELECTION_OF_ALL: 'TODOS_UPDATE_SELECTION_OF_ALL',
  USER_SET: 'USER_SET'
};
