export const actions = {
  TOAST_ADD: 'TOAST_ADD',
  TOAST_REMOVE_OLDEST: 'TOAST_REMOVE_OLDEST',
  TODOS_ADD: 'TODOS_ADD',
  TODOS_POPULATE: 'TODOS_POPULATE',
  TODOS_UPDATE_SELECTION: 'TODOS_UPDATE_SELECTION',
  TODOS_UPDATE_SELECTION_OF_ALL: 'TODOS_UPDATE_SELECTION_OF_ALL',
  TODOS_UPDATE_STATUS: 'TODOS_UPDATE_STATUS',
  TODOS_UPDATE_STATUS_OF_SELECTED: 'TODOS_UPDATE_STATUS_OF_SELECTED'
};
