export const actions = {
  THEME_UPDATE: 'THEME_UPDATE',
  TOAST_ADD: 'TOAST_ADD',
  TOAST_REMOVE_OLDEST: 'TOAST_REMOVE_OLDEST',
  TODOS_ADD: 'TODOS_ADD',
  TODOS_POPULATE: 'TODOS_POPULATE',
  TODOS_UPDATE_STATUS: 'TODOS_UPDATE_STATUS'
};
